# 4-1. 인구현황 데이터 분석
* data/인구현황.csv 를 사용하세요
* 연습문제/인구현황분석.ipynb  코드를 완성하세요.

## 1. 지역별 총인구수 Top5

In [ ]:
import pandas as pd

# .csv file 읽어오기
data = pd.read_csv('../data/인구현황.csv')
#print(data.shape)
#print(type(data))
#print(data)

# 컬럼명 확인하기
print(f'컬럼명 = {data.columns}')
#print(data['행정기관'])
# '행정기관' 컬럼에서 '시' 또는 '도'로 끝나는 항목만 필터링
sido_df = data[data['행정기관'].str.endswith(('시', '도'))]
#print(sido_df['행정기관'])

# 지역별 총인구수 TOP5만 출력
sido_df.loc[:, ['행정기관', '총인구수']].sort_values(['총인구수'], ascending=False).head(5)

(18, 8)
<class 'pandas.core.frame.DataFrame'>
컬럼명 = Index(['행정기관코드', '행정기관', '총인구수', '세대수', '세대당 인구', '남자 인구수', '여자 인구수', '남여 비율'], dtype='object')

     행정기관      총인구수
9     경기도  13694685
1   서울특별시   9331828
2   부산광역시   3266598
16   경상남도   3228380
4   인천광역시   3021010

       행정기관      총인구수
0        전국  51217221
9       경기도  13694685
1     서울특별시   9331828
2     부산광역시   3266598
16     경상남도   3228380
4     인천광역시   3021010
15     경상북도   2531384
3     대구광역시   2363629
12     충청남도   2136574
14     전라남도   1788819
13  전북특별자치도   1738690
11     충청북도   1591177
10  강원특별자치도   1517766
6     대전광역시   1439157
5     광주광역시   1408422
7     울산광역시   1098049
17  제주특별자치도    670368
8   세종특별자치시    390685

### 1-1. 지역별 총인구수 plot

## 2. 세대당 인구수 높은 지역 Top5

### 2-1. 지역별 세대당 인구 Plot

## 3. 남녀 비율 분석

### 3-1. 남녀 비율 분석 Plot

## 4. 남자초과 / 여자초과 분석

## 5. 세대당 인구 평균보다 높은 지역

### 5-1.   남초 vs 여초 개수 Plot  ( seaborn의 countplot )
         지역별 세대수 Plot ( seaborn의 barplot )